application: juicetestapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /rcvr/receiver.html
  static_files: index.html
  upload: index.html
  
- url: /rcvr/chrome_loading.gif
  static_files: chrome_loading.gif
  upload: chrome_loading.gif
